<?php
/**
 * Created by PhpStorm.
 * User: mrvjc
 * Date: 6/12/2015
 * Time: 11:22
 */
class SM_XPos_Block_Adminhtml_Sales_Order_Totals extends Mage_Adminhtml_Block_Sales_Order_Totals {
    protected function _initTotals()
    {
        Mage_Adminhtml_Block_Sales_Totals::_initTotals();

        $totalsBlock = $this->getParentBlock();
        $order = $totalsBlock->getOrder();
         // TODO: Change the autogenerated
        $this->_totals['paid'] = new Varien_Object(array(
            'code'      => 'paid',
            'strong'    => true,
            'value'     => $this->getSource()->getTotalPaid(),
            'base_value'=> $this->getSource()->getBaseTotalPaid(),
            'label'     => $this->helper('sales')->__('Total Paid'),
            'area'      => 'footer'
        ));

        if ($order->getRewardpointsSpent()) {
            $this->_totals['rewardpoints_spent_label'] = new Varien_Object(array(
                'code' => 'rewardpoints_spent_label',
                'strong' => true,
                'is_formated' => true,
                'value' => $order->getRewardpointsSpent(),
                'label' => $this->helper('sales')->__('Spent Points'),
                'area' => 'footer'
            ));
        }
        if ($order->getRewardpointsEarn()) {
            $this->_totals['rewardpoints_earn_label'] = new Varien_Object(array(
                'code' => 'rewardpoints_earn_label',
                'strong' => true,
                'is_formated' => true,
                'value' => $order->getRewardpointsEarn(),
                'label' => $this->helper('sales')->__('Earned Points'),
                'area' => 'footer'
            ));
        }
        $this->_totals['refunded'] = new Varien_Object(array(
            'code'      => 'refunded',
            'strong'    => true,
            'value'     => $this->getSource()->getTotalRefunded(),
            'base_value'=> $this->getSource()->getBaseTotalRefunded(),
            'label'     => $this->helper('sales')->__('Total Refunded'),
            'area'      => 'footer'
        ));
        $this->_totals['due'] = new Varien_Object(array(
            'code'      => 'due',
            'strong'    => true,
            'value'     => $this->getSource()->getTotalDue(),
            'base_value'=> $this->getSource()->getBaseTotalDue(),
            'label'     => $this->helper('sales')->__('Total Due'),
            'area'      => 'footer'
        ));
        return $this;
    }
}
