<?php
/**
 * Created by IntelliJ IDEA.
 * User: vjcspy
 * Date: 12/30/15
 * Time: 2:16 PM
 */ 
class SM_XPos_Block_Adminhtml_Sales_Items_Column_Name extends Mage_Adminhtml_Block_Sales_Items_Column_Name {
    /**
     * Set path to template used for generating block's output.
     *
     * @param string $template
     * @return Mage_Core_Block_Template
     */
    public function setTemplate($template) {
        return parent::setTemplate('sm/xpos/adminhtml/override/name.phtml'); // TODO: Change the autogenerated stub
    }

}
